---
title: "Reference file for NHSplots development"
subtitle: "Standard Visualisations in Q-Markdown"
author: "NHSE-R"
date: "`r Sys.Date()`"
format:
  html:
    mainfont: "Helvetica Neue"
    # Table of Contents options
    toc: true
    toc-depth: 2
    toc-location: left
    toc-title: Contents
    number-sections: true
    number-depth: 3
    # Render options
    theme: cosmo
    anchor-sections: true
    html-math-method: katex
    # Code options
    code-tools:
      source: false
      toggle: false
      caption: none
    code-fold: true
    code-summary: "Show code"
    self-contained: true
    self-contained-math: true
    # URL options
    link-external-icon: true
    link-external-newwindow: true
    # References
    citations-hover: true
    footnotes-hover: true
    bibliography: references/library.bib
---

# Visualisations

```r
#load packages
library(tidyverse)
library(dplyr)
library(bbplot)
library(gapminder)
```

```{r load library}
#| include: False

#load packages
library(tidyverse)
library(dplyr)
library(bbplot)
library(gapminder)
```

## Bar Charts

Reference (see @fig-barchart).

```{r fig-barchart}
#| label: fig-barchart
#| fig-cap: Life Expectancy in Africa, 2007. Data source [@gapminder]
#| warning: false

#Prepare data
bar_df <- gapminder %>%
  filter(year == 2007 & continent == "Africa") %>%
  arrange(desc(lifeExp)) %>%
  head(5)

#Make plot
ggplot(bar_df, aes(x = reorder(country, desc(lifeExp)), y = lifeExp)) +
  geom_bar(stat="identity", 
           position="identity", 
           fill="#1380A1") +
  # theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1)) +
  geom_hline(yintercept = 0, size = 1, colour="#333333") +
  bbc_style() +
  labs(title="Bar Chart Title",
       subtitle = "Bar Chart Sub-Title")
```

### Bar chart with highligted value

```{r fig-barchart-highlight}
#| label: fig-barchart-highlight
#| fig-cap: Life Expectancy in Africa, 2007. Data source [@gapminder]
#| warning: false

#Prepare data
bar_df <- gapminder %>%
  filter(year == 2007 & continent == "Africa") %>%
  arrange(desc(lifeExp)) %>%
  head(5)

# Find max life expectancy
maxLife <- bar_df[which.max(bar_df$lifeExp), ]

#Make plot
ggplot(bar_df, aes(x = reorder(country, desc(lifeExp)), y = lifeExp)) +
  geom_bar(stat="identity", 
           position="identity", 
           fill="#1380A1") +
  geom_bar(stat="identity", position="identity", fill=ifelse(bar_df$country == maxLife$country, "#1380A1", "#dddddd")) +
  geom_hline(yintercept = 0, size = 1, colour="#333333") +
  bbc_style() +
  labs(subtitle = paste(
            "Life expectancy in",
            maxLife$country,
            "is",
            format(round(maxLife$lifeExp, 0), nsmall = 0),
            "Years"
            )
       )
```

### Horizontal Bar Chart

```{r fig-barchart-horizontal}
#| label: fig-barchart-horizontal
#| fig-cap: Life Expectancy in Africa, 2007. Data source [@gapminder]
#| warning: false

#Prepare data
bar_df <- gapminder %>%
  filter(year == 2007 & continent == "Africa") %>%
  arrange(desc(lifeExp)) %>%
  head(5)

#Make plot
ggplot(bar_df, aes(x = reorder(country, lifeExp), y = lifeExp)) +
  geom_bar(stat="identity", 
           position="identity", 
           fill="#1380A1") +
  # theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1)) +
  geom_hline(yintercept = 0, size = 1, colour="#333333") +
  bbc_style() +
  coord_flip() +
  theme(panel.grid.major.x = element_line(color="#cbcbcb"), 
        panel.grid.major.y=element_blank()) 
```

## Line Charts

```{r fig-linechart}
#| label: fig-linechart
#| fig-cap: Life expectancy in Malawi 1952-2007. Data source [@gapminder]
#| warning: false

#Prepare data
line_df <- gapminder %>%
  filter(country == "Malawi") 

#Make plot
ggplot(line_df, aes(x = year, y = lifeExp)) +
  geom_line(colour = "#1380A1", size = 1) +
  geom_hline(yintercept = 0, size = 1, colour="#333333") +
  bbc_style() +
  ylim(c(0, max(line_df$lifeExp)+10)) + # add space above line
  labs(title="Line Chart Title",
       subtitle = "Line Chart Sub-Title")
```

### Line chart with latest value KPI

```{r fig-linechart-kpi}
#| label: fig-linechart-kpi
#| fig-cap: Life expectancy in Malawi 1952-2007. Data source [@gapminder]
#| warning: false

#Prepare data
line_df <- gapminder %>%
  filter(country == "Malawi")

# get latest metric value for KPI
latestDate <- max(line_df$year)
latestDate_value <- line_df %>% 
      filter(year == latestDate)

#Make plot
ggplot(line_df, aes(x = year, y = lifeExp)) +
  geom_line(colour = "#1380A1", size = 1) +
  geom_hline(yintercept = 0, size = 1, colour="#333333") +
  bbc_style() +
  ylim(c(0, max(line_df$lifeExp)+10)) + # add space above line
  labs(subtitle = paste(
            "Life expectancy in Malawi is",
            format(round(latestDate_value$lifeExp, 0), nsmall = 0),
            "as of",
            format(latestDate, format="%Y")
       )
  )
```

**todo:** 

1. Function to create KPI sub-titles

### Line chart with target line and lable

```{r fig-linechart-target}
#| label: fig-linechart-target
#| fig-cap: Life expectancy in Malawi 1952-2007. Data source [@gapminder]
#| warning: false

#Prepare data
line_df <- gapminder %>%
  filter(country == "Malawi")

# get latest metric value for KPI
latestDate <- max(line_df$year)
latestDate_value <- line_df %>% 
      filter(year == latestDate)

#Make plot
ggplot(line_df, aes(x = year, y = lifeExp)) +
  geom_line(colour = "#1380A1", size = 1) +
  geom_hline(yintercept = 0, size = 1, colour="#333333") +
  geom_hline(yintercept=45,  # taget line options
      linetype='dashed',
      size = 1.5,
      colour='#425563') +
  geom_label(                # taget lable options
      aes(
            x = 1952,
            y = 45, label = "Target (45 Years)"
      ),
      hjust = 0.15, 
      vjust = -.3, 
      colour = "#425563", 
      fill = "white", 
      label.size = NA, 
      family="Helvetica", 
      size = 6) +
  bbc_style() +
  ylim(c(0, max(line_df$lifeExp)+10)) # add space above line
```

**todo:** 

1. Function to add target as variable with adjustments

## References

::: {#refs}
:::