---
title: NHS Colour Guidlines
subtitle: "Colour is a key element of any organisation’s identity."
---

<style>
    .colourCore {
        text-align: left;
    }
    .colourCore tr:nth-child(1) { background: #005EB8; color: #FFFFFF;}
    .colourCore tr:nth-child(2) { background: #FFFFFF; color: #231f20;}

    .colourBlue {
        text-align: left;
    }
    .colourBlue tr:nth-child(1) { background: #003087; color: #FFFFFF;}
    .colourBlue tr:nth-child(2) { background: #0072CE; color: #FFFFFF;}
    .colourBlue tr:nth-child(3) { background: #41B6E6; color: #FFFFFF;}
    .colourBlue tr:nth-child(4) { background: #00A9CE; color: #FFFFFF;}

    .colourNeutral {
        text-align: left;
    }
    .colourNeutral tr:nth-child(1) { background: #231f20; color: #FFFFFF;}
    .colourNeutral tr:nth-child(2) { background: #425563; color: #FFFFFF;}
    .colourNeutral tr:nth-child(3) { background: #768692; color: #FFFFFF;}
    .colourNeutral tr:nth-child(4) { background: #E8EDEE; color: #231f20;}

    .colourGreen {
        text-align: left;
    }
    .colourGreen tr:nth-child(1) { background: #006747; color: #FFFFFF;}
    .colourGreen tr:nth-child(2) { background: #009639; color: #FFFFFF;}
    .colourGreen tr:nth-child(3) { background: #78BE20; color: #FFFFFF;}
    .colourGreen tr:nth-child(4) { background: #00A499; color: #FFFFFF;}

    .colourHighlight {
        text-align: left;
    }
    .colourHighlight tr:nth-child(1) { background: #003087; color: #FFFFFF;}
    .colourHighlight tr:nth-child(2) { background: #7C2855; color: #FFFFFF;}
    .colourHighlight tr:nth-child(3) { background: #AE2573; color: #FFFFFF;}
    .colourHighlight tr:nth-child(4) { background: #8A1538; color: #FFFFFF;}
    .colourHighlight tr:nth-child(5) { background: #DA291C; color: #FFFFFF;}
    .colourHighlight tr:nth-child(6) { background: #ED8B00; color: #FFFFFF;}
    .colourHighlight tr:nth-child(7) { background: #FFB81C; color: #231f20;}
    .colourHighlight tr:nth-child(8) { background: #FAE100; color: #231f20;}

    .colourRegion {
        text-align: left;
    }
    .colourRegion th {
                        background-color: #FFFFFF !important;
                        color: #231f20;
                    }
    .colourRegion tr:nth-child(1) { background: #3DB4F5; color: #FFFFFF;}
    .colourRegion tr:nth-child(2) { background: #820F25; color: #FFFFFF;}
    .colourRegion tr:nth-child(3) { background: #087558; color: #FFFFFF;}
    .colourRegion tr:nth-child(4) { background: #E69F00; color: #231f20;}
    .colourRegion tr:nth-child(5) { background: #EADC17; color: #FFFFFF;}
    .colourRegion tr:nth-child(6) { background: #6F00D5; color: #FFFFFF;}
    .colourRegion tr:nth-child(7) { background: #6F7D86; color: #FFFFFF;}
</style>

The colours in the NHS colour palette all offer at least an AA accessibility rating, with many offering the maximum AAA rating when used with sufficient contrasts on appropriate backgrounds.

[> Read the Official NHS Guidance](https://www.england.nhs.uk/nhsidentity/identity-guidelines/colours/)

### Core NHS colours
<div class="colourCore">
| | |
| -- | -- |
| NHS Blue | #005EB8 |
| White | #FFFFFF |
</div>

The core NHS Blue and white are supported by four other groups of colours in the NHS colour palette, to provide NHS organisations with the flexibility to differentiate their communications from each other, but not from the NHS.

### Level 1: NHS blues
<div class="colourBlue">
| | |
| -- | -- |
| NHS Dark Blue | #003087 |
| NHS Bright Blue | #0072CE |
| NHS Light Blue | #41B6E6 |
| NHS Aqua Blue | #00A9CE |
</div>

This is the top level palette that reinforces people's association with blue and white. There are a number of hues to support the main NHS Blue colour to give lighter and darker alternatives to add tonal variety.

### Level 2: NHS neutrals
<div class="colourNeutral">
| | |
| -- | -- |
| NHS Black | #231f20 |
| NHS Dark Grey | #425563 |
| NHS Mid Grey | #768692 |
| NHS Pale grey | #E8EDEE |
</div>

These colours help to support the top level blues. Black and dark grey can be used for type, depending on the background and application. The lighter greys can be used as backgrounds when they are appropriate and are useful online colours. White is, of course, the most important neutral base. These colours will support the overall blue and white look if they are used with the proper emphasis.

### Level 3: NHS support greens
<div class="colourGreen">
| | |
| -- | -- |
| NHS Dark Green | #006747 |
| NHS Green | #009639 |
| NHS Light Green | #78BE20 |
| NHS Aqua Green | #00A499 |
</div>

Green is close to blue in the colour spectrum and gives a feel of being in the same colour family. Therefore, when they are used moderately and in a secondary support role, they will not compromise the strong associations people have with blue and white. However, if it becomes too dominant it will impact on people’s ability to instantly recognise the NHS as being the source of the information.

### Level 4: NHS highlights
<div class="colourHighlight">
| | |
| -- | -- |
| NHS Purple | #003087 |
| Dark Pink | #7C2855 |
| NHS Pink | #AE2573 |
| NHS Dark Red | #8A1538 |
| Emergency Services Red | #DA291C |
| NHS Orange | #ED8B00 |
| NHS Warm Yellow | #FFB81C |
| NHS Yellow | #FAE100 |
</div>

Highlights are very useful for drawing attention to details, helping to warm up the blue look and providing accent colours to enable NHS organisations, partnerships and services to differentiate themselves from each other. However, they should not be used too heavily otherwise they change the overall look dramatically and people will not associate your communication with the NHS. Therefore, use minimally and do not use large blocks of these highlight colours.

The highlight colour ‘Emergency Services Red’ is not exclusively for use in relation to emergency and urgent care services. However, because of its strong association and use in this area, you should carefully consider how you use it for other purposes.

## NHS Region Colours
<div class="colourRegion">
ODS Code | NHS Code | Region | Hex |
-- | -- |-- | -- |
E40000003 | Y56 | London | #3DB4F5 |
E40000006 | Y58 | South West | #820F25 |
E40000005 | Y59 | South East | #087558 |
E40000011 | Y60 | Midlands | #E69F00 |
E40000007 | Y61 | East of England | #EADC17 |
E40000010 | Y62 | North West | #6F00D5 |
E40000012 | Y63 | North East & Yorkshire | #6F7D86 |
</div>